name: Build & Push Nuxt App to Amazon ECR

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      GITHUB_OIDC_ROLE: ${{ secrets.AWS_GITHUB_OIDC_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: ${{ env.GITHUB_OIDC_ROLE }}
        role-session-name: GitHubActionsSession

    - name: Login to Amazon ECR Private Registry
      uses: aws-actions/amazon-ecr-login@v2
      id: login-ecr

    - name: Build and push Docker image
      run: |
        docker build -t $ECR_REPOSITORY:latest .
        docker push $ECR_REPOSITORY:latest